apiVersion: bss.localhost/v1alpha1
kind: BssCluster
metadata:
  labels:
    app.kubernetes.io/name: bss-operator
    app.kubernetes.io/managed-by: kustomize
  name: bsscluster-sample
spec:
  replicas: 2
  image: nginx:latest
