apiVersion: bss.localhost/v1alpha1
kind: BSSQuery
metadata:
  labels:
    app.kubernetes.io/name: bss-operator
    app.kubernetes.io/managed-by: kustomize
  name: bssquery-sample-clusters
spec:
  apiEndpoint: "http://bss-api.default.svc.cluster.local:8880/graphql"
  query: clusters
  refreshInterval: 60
